export const seedProductNames = [
    // ==========================================
    // HUGO BOSS
    // ==========================================
    { brand: "Hugo Boss", gender: "men", name: "Slim-Fit Suit in Virgin Wool" },
    { brand: "Hugo Boss", gender: "men", name: "Passenger Cotton Piqué Polo Shirt" },
    { brand: "Hugo Boss", gender: "men", name: "Regular-Fit Poplin Formal Shirt" },
    { brand: "Hugo Boss", gender: "men", name: "Delaware Slim-Fit Stretch Jeans" },
    { brand: "Hugo Boss", gender: "men", name: "Schino Slim-Fit Chino Trousers" },
    { brand: "Hugo Boss", gender: "men", name: "Athleisure Zip-Up Cotton Hoodie" },
    { brand: "Hugo Boss", gender: "men", name: "Water-Repellent Technical Field Jacket" },
    { brand: "Hugo Boss", gender: "men", name: "Cashmere-Blend Crew-Neck Sweater" },
    { brand: "Hugo Boss", gender: "men", name: "Mercerized Cotton Premium T-Shirt" },
    { brand: "Hugo Boss", gender: "men", name: "Classic Wool-Blend Double-Breasted Overcoat" },
    { brand: "Hugo Boss", gender: "men", name: "Identity Leather Bomber Jacket" },
    { brand: "Hugo Boss", gender: "men", name: "Maine Regular-Fit Straight Jeans" },
    { brand: "Hugo Boss", gender: "men", name: "Tailored Linen-Blend Summer Blazer" },
    { brand: "Hugo Boss", gender: "men", name: "C-Buster Regular-Fit Oxford Shirt" },
    { brand: "Hugo Boss", gender: "men", name: "Pixel Logo Print Sweatshirt" },
    { brand: "Hugo Boss", gender: "men", name: "Zipped Track Jacket with Contrast Piping" },
    { brand: "Hugo Boss", gender: "men", name: "Soft Suede Chelsea Boots" },

    { brand: "Hugo Boss", gender: "women", name: "Slim-Fit Blazer in Stretch Crepe" },
    { brand: "Hugo Boss", gender: "women", name: "A-Line Dress in Fluid Fabric" },
    { brand: "Hugo Boss", gender: "women", name: "Tailored Trousers in Virgin Wool" },
    { brand: "Hugo Boss", gender: "women", name: "Silk-Blend V-Neck Elegant Blouse" },
    { brand: "Hugo Boss", gender: "women", name: "Soft Leather Biker Jacket" },
    { brand: "Hugo Boss", gender: "women", name: "Pleated Midi Skirt with Satin Finish" },
    { brand: "Hugo Boss", gender: "women", name: "Double-Breasted Wool Wrap Coat" },
    { brand: "Hugo Boss", gender: "women", name: "Fine-Knit Mock-Neck Cashmere Sweater" },
    { brand: "Hugo Boss", gender: "women", name: "Cotton-Blend Classic Trench Coat" },
    { brand: "Hugo Boss", gender: "women", name: "Wrap Dress in Printed Pure Silk" },
    { brand: "Hugo Boss", gender: "women", name: "High-Waisted Tailored City Shorts" },
    { brand: "Hugo Boss", gender: "women", name: "Ribbed Knit Open-Front Cardigan" },
    { brand: "Hugo Boss", gender: "women", name: "Point-Collar Cotton Poplin Shirt" },
    { brand: "Hugo Boss", gender: "women", name: "Stretch-Cotton Slim-Fit Trousers" },
    { brand: "Hugo Boss", gender: "women", name: "Evening Gown with Draped Detail" },
    { brand: "Hugo Boss", gender: "women", name: "Monogram Embossed Leather Shopper" },
    { brand: "Hugo Boss", gender: "women", name: "Pointed-Toe Leather Pumps" },

    // ==========================================
    // GUESS
    // ==========================================
    { brand: "Guess", gender: "men", name: "Super Slim Distressed Denim Jacket" },
    { brand: "Guess", gender: "men", name: "Eco Brenton Triangle Logo T-Shirt" },
    { brand: "Guess", gender: "men", name: "Angels Slim-Fit Tapered Jeans" },
    { brand: "Guess", gender: "men", name: "Poplin Striped Casual Shirt" },
    { brand: "Guess", gender: "men", name: "Suede Bomber Jacket with Ribbed Trim" },
    { brand: "Guess", gender: "men", name: "Chris Classic Denim Western Shirt" },
    { brand: "Guess", gender: "men", name: "Front Logo Fleece Pullover Hoodie" },
    { brand: "Guess", gender: "men", name: "Slim Fit Chino Cargo Trousers" },
    { brand: "Guess", gender: "men", name: "Lightweight High-Shine Puffer Jacket" },
    { brand: "Guess", gender: "men", name: "Vintage Foil Logo Sweatshirt" },
    { brand: "Guess", gender: "men", name: "Contrast Stitching Polo Shirt" },
    { brand: "Guess", gender: "men", name: "Sateen Relaxed Fit Cargo Pants" },
    { brand: "Guess", gender: "men", name: "Active Nylon Zip-Up Track Jacket" },
    { brand: "Guess", gender: "men", name: "Los Angeles Graphic Crew-Neck Tee" },
    { brand: "Guess", gender: "men", name: "Destroyed Detail Denim Shorts" },
    { brand: "Guess", gender: "men", name: "Corduroy Overshirt with Pockets" },
    { brand: "Guess", gender: "men", name: "Urban Camo Windbreaker Jacket" },

    { brand: "Guess", gender: "women", name: "Eco Seductive High-Rise Skinny Jeans" },
    { brand: "Guess", gender: "women", name: "Triangle Logo Knit Bodysuit" },
    { brand: "Guess", gender: "women", name: "Marciano Bandage Bodycon Dress" },
    { brand: "Guess", gender: "women", name: "Faux-Leather Moto Jacket with Hardware" },
    { brand: "Guess", gender: "women", name: "High-Rise Distressed Denim Shorts" },
    { brand: "Guess", gender: "women", name: "Rhinestone Logo Fitted T-Shirt" },
    { brand: "Guess", gender: "women", name: "Ribbed Knit Midi Dress with Slit" },
    { brand: "Guess", gender: "women", name: "Tweed Cropped Blazer Jacket" },
    { brand: "Guess", gender: "women", name: "Satin V-Neck Lace Camisole" },
    { brand: "Guess", gender: "women", name: "Wide-Leg Fluid Cargo Trousers" },
    { brand: "Guess", gender: "women", name: "Hooded Longline Metallic Puffer Coat" },
    { brand: "Guess", gender: "women", name: "Animal Print Chiffon Maxi Dress" },
    { brand: "Guess", gender: "women", name: "Off-The-Shoulder Smocked Top" },
    { brand: "Guess", gender: "women", name: "Metallic Thread Party Cocktail Dress" },
    { brand: "Guess", gender: "women", name: "Monogram Print Crossbody Bag" },
    { brand: "Guess", gender: "women", name: "Cropped Denim Trucker Jacket" },
    { brand: "Guess", gender: "women", name: "Knit Logo Tape Leggings" },

    // ==========================================
    // G-STAR RAW
    // ==========================================
    { brand: "G-Star RAW", gender: "men", name: "3301 Straight Tapered Raw Denim Jeans" },
    { brand: "G-Star RAW", gender: "men", name: "D-Staq 3D Slim Fit Jeans" },
    { brand: "G-Star RAW", gender: "men", name: "Arc 3D Pilot Denim Jacket" },
    { brand: "G-Star RAW", gender: "men", name: "Raw Cargo Trousers with Multi-Pockets" },
    { brand: "G-Star RAW", gender: "men", name: "Lash Graphic Clean T-Shirt" },
    { brand: "G-Star RAW", gender: "men", name: "Meefic Hooded Lightweight Puffer Jacket" },
    { brand: "G-Star RAW", gender: "men", name: "Scutar Utility Tailored Blazer" },
    { brand: "G-Star RAW", gender: "men", name: "Vetar Slim Micro-Sanding Chinos" },
    { brand: "G-Star RAW", gender: "men", name: "Core Straight Denim Long Sleeve Shirt" },
    { brand: "G-Star RAW", gender: "men", name: "Revend Super Skinny Fit Jeans" },
    { brand: "G-Star RAW", gender: "men", name: "Type C 3D Loose Tapered Pants" },
    { brand: "G-Star RAW", gender: "men", name: "Holorn Logo Print Heavyweight Hoodie" },
    { brand: "G-Star RAW", gender: "men", name: "Rackam Zip-Through Bomber Jacket" },
    { brand: "G-Star RAW", gender: "men", name: "Overshirt with 3D Cargo Pockets" },
    { brand: "G-Star RAW", gender: "men", name: "Utility Belted Field Jacket" },
    { brand: "G-Star RAW", gender: "men", name: "G-Star Elwood 5620 3D Tapered" },
    { brand: "G-Star RAW", gender: "men", name: "Stripe Graphic Crewneck Sweatshirt" },

    { brand: "G-Star RAW", gender: "women", name: "3301 High-Waist Flare Jeans" },
    { brand: "G-Star RAW", gender: "women", name: "Kafey Ultra High-Rise Skinny Jeans" },
    { brand: "G-Star RAW", gender: "women", name: "Deck Ultra High Wide-Leg Denim" },
    { brand: "G-Star RAW", gender: "women", name: "Lynn Mid-Rise Skinny Fit Jeans" },
    { brand: "G-Star RAW", gender: "women", name: "Multi Cord Heavy Oversized Hoodie" },
    { brand: "G-Star RAW", gender: "women", name: "Midge Cody Mid Skinny Jeans" },
    { brand: "G-Star RAW", gender: "women", name: "Utility Denim Zip-Up Jumpsuit" },
    { brand: "G-Star RAW", gender: "women", name: "Slim Fit Ribbed High-Neck Top" },
    { brand: "G-Star RAW", gender: "women", name: "Jane Boyfriend Denim Blazer" },
    { brand: "G-Star RAW", gender: "women", name: "Cropped Denim Workwear Shirt" },
    { brand: "G-Star RAW", gender: "women", name: "E-Windbreaker Hooded Mesh Jacket" },
    { brand: "G-Star RAW", gender: "women", name: "Cargo Satin Utility Midi Skirt" },
    { brand: "G-Star RAW", gender: "women", name: "High-Waisted Chino Summer Shorts" },
    { brand: "G-Star RAW", gender: "women", name: "Boyfriend Block Logo T-Shirt" },
    { brand: "G-Star RAW", gender: "women", name: "Hardcore Denim Mini Skirt" },
    { brand: "G-Star RAW", gender: "women", name: "Strett Poplin Bomber Jacket" },
    { brand: "G-Star RAW", gender: "women", name: "Lash Loose Knit Sweater" },

    // ==========================================
    // LEVI'S
    // ==========================================
    { brand: "Levi's", gender: "men", name: "501 Original Fit Selvedge Jeans" },
    { brand: "Levi's", gender: "men", name: "511 Slim Fit All-Season Tech Jeans" },
    { brand: "Levi's", gender: "men", name: "512 Slim Taper Fit Denim" },
    { brand: "Levi's", gender: "men", name: "Barstow Western Denim Work Shirt" },
    { brand: "Levi's", gender: "men", name: "Jackson Worker Flannel Overshirt" },
    { brand: "Levi's", gender: "men", name: "The Original Trucker Jacket" },
    { brand: "Levi's", gender: "men", name: "Graphic Sportswear Crewneck Sweatshirt" },
    { brand: "Levi's", gender: "men", name: "502 Regular Taper Fit Chinos" },
    { brand: "Levi's", gender: "men", name: "XX Chino Slim Taper Pants" },
    { brand: "Levi's", gender: "men", name: "Sherpa Lined Denim Trucker Jacket" },
    { brand: "Levi's", gender: "men", name: "Thermore Quilted Puffer Jacket" },
    { brand: "Levi's", gender: "men", name: "Solid Housemark Cotton Polo Shirt" },
    { brand: "Levi's", gender: "men", name: "527 Slim Bootcut Fit Jeans" },
    { brand: "Levi's", gender: "men", name: "Vintage Clothing 1950s Sportswear Tee" },
    { brand: "Levi's", gender: "men", name: "Canvas Utility Chore Jacket" },
    { brand: "Levi's", gender: "men", name: "541 Athletic Taper Fit Jeans" },
    { brand: "Levi's", gender: "men", name: "Batwing Logo Graphic T-Shirt" },

    { brand: "Levi's", gender: "women", name: "501 Original Cropped Jeans" },
    { brand: "Levi's", gender: "women", name: "Ribcage Straight Ankle High-Rise Jeans" },
    { brand: "Levi's", gender: "women", name: "721 High-Rise Skinny Jeans" },
    { brand: "Levi's", gender: "women", name: "Ex-Boyfriend Oversized Trucker Jacket" },
    { brand: "Levi's", gender: "women", name: "Retro Graphic Surf Tee" },
    { brand: "Levi's", gender: "women", name: "311 Shaping Skinny Fit Jeans" },
    { brand: "Levi's", gender: "women", name: "Wedgie Straight Fit Denim" },
    { brand: "Levi's", gender: "women", name: "Ultimate Denim Western Shirt" },
    { brand: "Levi's", gender: "women", name: "Tailored Utility Workwear Jumpsuit" },
    { brand: "Levi's", gender: "women", name: "Ribcage Wide-Leg Denim Trousers" },
    { brand: "Levi's", gender: "women", name: "Cozy Up Sherpa Hooded Jacket" },
    { brand: "Levi's", gender: "women", name: "Iconic Denim Deconstructed Midi Skirt" },
    { brand: "Levi's", gender: "women", name: "720 High-Rise Super Skinny Jeans" },
    { brand: "Levi's", gender: "women", name: "High-Waisted 501 Original Denim Shorts" },
    { brand: "Levi's", gender: "women", name: "Pleated Balloon Cotton Pants" },
    { brand: "Levi's", gender: "women", name: "Perfect Tee Classic V-Neck" },
    { brand: "Levi's", gender: "women", name: "Premium Utility Chore Coat" },

    // ==========================================
    // NIKE
    // ==========================================
    { brand: "Nike", gender: "men", name: "Air Max 90 Retro Sneakers" },
    { brand: "Nike", gender: "men", name: "Dri-FIT ADV Training T-Shirt" },
    { brand: "Nike", gender: "men", name: "Tech Fleece Full-Zip Hooded Jacket" },
    { brand: "Nike", gender: "men", name: "Club Fleece Tapered Joggers" },
    { brand: "Nike", gender: "men", name: "Air Force 1 '07 Basketball Shoes" },
    { brand: "Nike", gender: "men", name: "Challenger 7-Inch Running Shorts" },
    { brand: "Nike", gender: "men", name: "Air Zoom Pegasus Running Shoes" },
    { brand: "Nike", gender: "men", name: "Therma-FIT Training Pullover Hoodie" },
    { brand: "Nike", gender: "men", name: "Windrunner Hooded Running Jacket" },
    { brand: "Nike", gender: "men", name: "Pro Combat Compression Tights" },
    { brand: "Nike", gender: "men", name: "Sportswear Club Embroidered Tee" },
    { brand: "Nike", gender: "men", name: "ZoomX Vaporfly Next% Racing Shoes" },
    { brand: "Nike", gender: "men", name: "SB Dunk Low Pro Skate Shoes" },
    { brand: "Nike", gender: "men", name: "Academy Soccer Training Pants" },
    { brand: "Nike", gender: "men", name: "Phenom Elite Knit Running Trousers" },
    { brand: "Nike", gender: "men", name: "Jordan Jumpman Graphic Fleece Hoodie" },
    { brand: "Nike", gender: "men", name: "Sportswear Reversible Bomber Jacket" },

    { brand: "Nike", gender: "women", name: "Air Max 270 Lifestyle Sneakers" },
    { brand: "Nike", gender: "women", name: "One Luxe High-Waisted Training Leggings" },
    { brand: "Nike", gender: "women", name: "Sportswear Phoenix Fleece Oversized Hoodie" },
    { brand: "Nike", gender: "women", name: "Dri-FIT One Slim Fit Tank Top" },
    { brand: "Nike", gender: "women", name: "Air Force 1 Shadow Platform Shoes" },
    { brand: "Nike", gender: "women", name: "Indy Medium-Support Sports Bra" },
    { brand: "Nike", gender: "women", name: "Tempo Brief-Lined Running Shorts" },
    { brand: "Nike", gender: "women", name: "Tech Fleece Tailored Trousers" },
    { brand: "Nike", gender: "women", name: "ZoomX Invincible Run Flyknit Shoes" },
    { brand: "Nike", gender: "women", name: "Pegasus Trail Waterproof Shoes" },
    { brand: "Nike", gender: "women", name: "Sportswear Essential Tight Crop Tee" },
    { brand: "Nike", gender: "women", name: "Yoga Luxe Infinalon Jumpsuit" },
    { brand: "Nike", gender: "women", name: "Element Crew-Neck Running Top" },
    { brand: "Nike", gender: "women", name: "Alate Minimalist Light-Support Bra" },
    { brand: "Nike", gender: "women", name: "Blazer Low '77 Vintage Sneakers" },
    { brand: "Nike", gender: "women", name: "Epic Fast Mesh Running Tights" },
    { brand: "Nike", gender: "women", name: "Sportswear Icon Clash Jersey Dress" },

    // ==========================================
    // THE NORTH FACE
    // ==========================================
    { brand: "The North Face", gender: "men", name: "1996 Retro Nuptse Down Jacket" },
    { brand: "The North Face", gender: "men", name: "Denali Recycled Fleece Jacket" },
    { brand: "The North Face", gender: "men", name: "McMurdo Down Waterproof Parka" },
    { brand: "The North Face", gender: "men", name: "Resolve Waterproof Hooded Shell Jacket" },
    { brand: "The North Face", gender: "men", name: "Apex Bionic Windproof Softshell Jacket" },
    { brand: "The North Face", gender: "men", name: "Exploration Stretch Cargo Trousers" },
    { brand: "The North Face", gender: "men", name: "Half Dome Pullover Fleece Hoodie" },
    { brand: "The North Face", gender: "men", name: "Paramount Trail Convertible Shorts" },
    { brand: "The North Face", gender: "men", name: "Simple Dome Cotton T-Shirt" },
    { brand: "The North Face", gender: "men", name: "Vectiv Taraval Hiking Shoes" },
    { brand: "The North Face", gender: "men", name: "Mountain Light Futurelight Jacket" },
    { brand: "The North Face", gender: "men", name: "Gordon Lyons Quarter-Zip Sweater" },
    { brand: "The North Face", gender: "men", name: "Dryzzle Futurelight Active Shell" },
    { brand: "The North Face", gender: "men", name: "Thermoball Eco Insulated Quilted Jacket" },
    { brand: "The North Face", gender: "men", name: "Antora Rain Waterproof Jacket" },
    { brand: "The North Face", gender: "men", name: "Steep Tech Heavyweight Sweatshirt" },
    { brand: "The North Face", gender: "men", name: "Base Camp Waterproof Duffel Bag" },

    { brand: "The North Face", gender: "women", name: "1996 Retro Nuptse Cropped Down Jacket" },
    { brand: "The North Face", gender: "women", name: "Denali Cropped Fleece Jacket" },
    { brand: "The North Face", gender: "women", name: "Metropolis Hooded Down Parka" },
    { brand: "The North Face", gender: "women", name: "Venture 2 Waterproof Rain Jacket" },
    { brand: "The North Face", gender: "women", name: "Apex Nimble Slim Softshell Jacket" },
    { brand: "The North Face", gender: "women", name: "Half Dome Crop Fleece Hoodie" },
    { brand: "The North Face", gender: "women", name: "Aphrodite Motion Hiking Trousers" },
    { brand: "The North Face", gender: "women", name: "Dune Sky Moisture-Wicking Tank Top" },
    { brand: "The North Face", gender: "women", name: "Vectiv Hypnum Trail Running Shoes" },
    { brand: "The North Face", gender: "women", name: "Mountain Sweatshirt Cozy Pullover" },
    { brand: "The North Face", gender: "women", name: "Hydrenalite Down Puffer Hoodie" },
    { brand: "The North Face", gender: "women", name: "Freedom Insulated Ski Pants" },
    { brand: "The North Face", gender: "women", name: "Osito High-Pile Fleece Jacket" },
    { brand: "The North Face", gender: "women", name: "Woodmont Long Waterproof Rain Parka" },
    { brand: "The North Face", gender: "women", name: "Class V Water-Repellent Shorts" },
    { brand: "The North Face", gender: "women", name: "Never Stop Utility Tote Bag" },
    { brand: "The North Face", gender: "women", name: "Sunriser Athletic Running Tee" },

    // ==========================================
    // ADIDAS
    // ==========================================
    { brand: "Adidas", gender: "men", name: "Ultraboost 1.0 Performance Sneakers" },
    { brand: "Adidas", gender: "men", name: "Originals Stan Smith Leather Shoes" },
    { brand: "Adidas", gender: "men", name: "Tiro 23 Athletic Track Pants" },
    { brand: "Adidas", gender: "men", name: "Essentials 3-Stripes Fleece Hoodie" },
    { brand: "Adidas", gender: "men", name: "Samba Classic Indoor Soccer Shoes" },
    { brand: "Adidas", gender: "men", name: "Supernova Moisture-Wicking Running T-Shirt" },
    { brand: "Adidas", gender: "men", name: "Originals Superstar Shell-Toe Shoes" },
    { brand: "Adidas", gender: "men", name: "Own The Run Lightweight Shorts" },
    { brand: "Adidas", gender: "men", name: "Terrex Free Hiker GORE-TEX Shoes" },
    { brand: "Adidas", gender: "men", name: "Adicolor Classics Firebird Track Jacket" },
    { brand: "Adidas", gender: "men", name: "Techfit Muscle Compression Tights" },
    { brand: "Adidas", gender: "men", name: "Trefoil Oversized Graphic Tee" },
    { brand: "Adidas", gender: "men", name: "Aeroready Training Full-Zip Hoodie" },
    { brand: "Adidas", gender: "men", name: "Terrex Rain.Rdy Waterproof Jacket" },
    { brand: "Adidas", gender: "men", name: "Run It Athletic Tank Top" },
    { brand: "Adidas", gender: "men", name: "Originals Beckenbauer Track Trousers" },
    { brand: "Adidas", gender: "men", name: "Power VI Heavy Sport Backpack" },

    { brand: "Adidas", gender: "women", name: "Ultraboost Light Running Shoes" },
    { brand: "Adidas", gender: "women", name: "Originals Stan Smith Platform Shoes" },
    { brand: "Adidas", gender: "women", name: "Tiro Track Trousers Regular Fit" },
    { brand: "Adidas", gender: "women", name: "Essentials High-Waisted Studio Leggings" },
    { brand: "Adidas", gender: "women", name: "Samba OG Retro Lifestyle Shoes" },
    { brand: "Adidas", gender: "women", name: "Run It Breathable Running T-Shirt" },
    { brand: "Adidas", gender: "women", name: "Originals Superstar Platform Women" },
    { brand: "Adidas", gender: "women", name: "Pacer 3-Stripes Woven Gym Shorts" },
    { brand: "Adidas", gender: "women", name: "Terrex Soulstride Trail Running Shoes" },
    { brand: "Adidas", gender: "women", name: "Adicolor Oversized Trefoil Fleece Hoodie" },
    { brand: "Adidas", gender: "women", name: "Techfit High-Waisted Volleyball Shorts" },
    { brand: "Adidas", gender: "women", name: "Trefoil Slim Fit Crop Tee" },
    { brand: "Adidas", gender: "women", name: "Yoga Studio Light-Support Sports Bra" },
    { brand: "Adidas", gender: "women", name: "Helionic Slim-Fit Down Vest" },
    { brand: "Adidas", gender: "women", name: "All Me Cross-Back Training Bra" },
    { brand: "Adidas", gender: "women", name: "Originals Formotion Sculpt Leggings" },
    { brand: "Adidas", gender: "women", name: "Stella McCartney Gym Duffel Bag" },

    // ==========================================
    // SCOTCH & SODA
    // ==========================================
    { brand: "Scotch & Soda", gender: "men", name: "Ralston Regular Slim Garment-Dyed Jeans" },
    { brand: "Scotch & Soda", gender: "men", name: "Classic Cotton-Twill Stretch Chinos" },
    { brand: "Scotch & Soda", gender: "men", name: "Printed Organic Cotton-Poplin Shirt" },
    { brand: "Scotch & Soda", gender: "men", name: "Structured Knit Crew-Neck Cotton Sweater" },
    { brand: "Scotch & Soda", gender: "men", name: "Lightweight Hooded City Windbreaker" },
    { brand: "Scotch & Soda", gender: "men", name: "Garment-Dyed Distressed Denim Jacket" },
    { brand: "Scotch & Soda", gender: "men", name: "Classic Fine-Corduroy Unstructured Blazer" },
    { brand: "Scotch & Soda", gender: "men", name: "Melange Wool-Blend Tailored Coat" },
    { brand: "Scotch & Soda", gender: "men", name: "Mercerized Cotton Pocket T-Shirt" },
    { brand: "Scotch & Soda", gender: "men", name: "Tailored Slim-Fit Waistcoat Vest" },
    { brand: "Scotch & Soda", gender: "men", name: "Tropical Print Quick-Dry Swim Shorts" },
    { brand: "Scotch & Soda", gender: "men", name: "Mott Super Slim-Fit Tailored Chino" },
    { brand: "Scotch & Soda", gender: "men", name: "Heavy Twill Worker Overshirt Jacket" },
    { brand: "Scotch & Soda", gender: "men", name: "Amsterdam Artwork Brushed Fleece Hoodie" },
    { brand: "Scotch & Soda", gender: "men", name: "Striped Lightweight Linen Summer Shirt" },
    { brand: "Scotch & Soda", gender: "men", name: "Suede Leather Derby Brogue Shoes" },
    { brand: "Scotch & Soda", gender: "men", name: "Classic Leather Belt with Engraved Buckle" },

    { brand: "Scotch & Soda", gender: "women", name: "Maison Scotch Super Skinny Jeans" },
    { brand: "Scotch & Soda", gender: "women", name: "Printed Ruffle V-Neck Midi Dress" },
    { brand: "Scotch & Soda", gender: "women", name: "Tailored Double-Breasted Structured Blazer" },
    { brand: "Scotch & Soda", gender: "women", name: "Silk-Blend Semi-Sheer Elegant Blouse" },
    { brand: "Scotch & Soda", gender: "women", name: "High-Waisted Wide-Leg Pleated Trousers" },
    { brand: "Scotch & Soda", gender: "women", name: "Oversized Cable-Knit Mohair Cardigan" },
    { brand: "Scotch & Soda", gender: "women", name: "Embroidered Denim Western Jacket" },
    { brand: "Scotch & Soda", gender: "women", name: "Metallic Pleated Shimmer Midi Skirt" },
    { brand: "Scotch & Soda", gender: "women", name: "Soft Premium Leather Biker Jacket" },
    { brand: "Scotch & Soda", gender: "women", name: "Boho Wrap Maxi Dress with Floral Print" },
    { brand: "Scotch & Soda", gender: "women", name: "Ribbed Mock-Neck Slim Cotton Top" },
    { brand: "Scotch & Soda", gender: "women", name: "Printed Organic Cotton Graphic Tee" },
    { brand: "Scotch & Soda", gender: "women", name: "Tailored Linen Shorts with Woven Belt" },
    { brand: "Scotch & Soda", gender: "women", name: "Lightweight Lyocell Belted Trench Coat" },
    { brand: "Scotch & Soda", gender: "women", name: "Patterned Kimono Jacket with Satin Trim" },
    { brand: "Scotch & Soda", gender: "women", name: "Soft Suede Pointed Ankle Boots" },
    { brand: "Scotch & Soda", gender: "women", name: "Statement Leather Waist Belt" },

    // ==========================================
    // CALVIN KLEIN
    // ==========================================
    { brand: "Calvin Klein", gender: "men", name: "Modern Cotton Boxer Briefs 3-Pack" },
    { brand: "Calvin Klein", gender: "men", name: "Monologo Organic Cotton Basic T-Shirt" },
    { brand: "Calvin Klein", gender: "men", name: "Skinny Fit Stretch Dark Wash Jeans" },
    { brand: "Calvin Klein", gender: "men", name: "Liquid Touch Premium Polo Shirt" },
    { brand: "Calvin Klein", gender: "men", name: "Institutional Block Logo Pullover Hoodie" },
    { brand: "Calvin Klein", gender: "men", name: "Structured Minimalist Two-Button Blazer" },
    { brand: "Calvin Klein", gender: "men", name: "Packable Lightweight Down Puffer Jacket" },
    { brand: "Calvin Klein", gender: "men", name: "Extra-Fine Merino Wool V-Neck Sweater" },
    { brand: "Calvin Klein", gender: "men", name: "Straight Fit Refined Chino Pants" },
    { brand: "Calvin Klein", gender: "men", name: "Microfiber Stretch Low-Rise Trunks" },
    { brand: "Calvin Klein", gender: "men", name: "90s Straight Rigid Denim Trucker Jacket" },
    { brand: "Calvin Klein", gender: "men", name: "Cotton Stretch Ultra-Soft Lounge Pants" },
    { brand: "Calvin Klein", gender: "men", name: "Monogram Crew-Neck Brushed Sweatshirt" },
    { brand: "Calvin Klein", gender: "men", name: "Technical Poplin Zip Bomber Jacket" },
    { brand: "Calvin Klein", gender: "men", name: "Canvas Low-Top Minimalist Sneakers" },
    { brand: "Calvin Klein", gender: "men", name: "Slim-Fit Stretch Poplin Dress Shirt" },
    { brand: "Calvin Klein", gender: "men", name: "Classic Reversible Smooth Leather Belt" },

    { brand: "Calvin Klein", gender: "women", name: "Modern Cotton Unlined Bralette" },
    { brand: "Calvin Klein", gender: "women", name: "High-Rise Skinny Sculpting Jeans" },
    { brand: "Calvin Klein", gender: "women", name: "Monologo Cropped Cotton T-Shirt" },
    { brand: "Calvin Klein", gender: "women", name: "CK One Unlined Plunge Wireless Bra" },
    { brand: "Calvin Klein", gender: "women", name: "Ribbed Knit Bodycon Midi Dress" },
    { brand: "Calvin Klein", gender: "women", name: "Oversized Denim Trucker Jacket" },
    { brand: "Calvin Klein", gender: "women", name: "Tailored Clean-Cut Boy Shirt" },
    { brand: "Calvin Klein", gender: "women", name: "High-Waisted Wide-Leg Fluid Trousers" },
    { brand: "Calvin Klein", gender: "women", name: "CK One Cotton Classic Thong" },
    { brand: "Calvin Klein", gender: "women", name: "Liquid Touch Short Sleeve Polo Dress" },
    { brand: "Calvin Klein", gender: "women", name: "Hooded Long Matte Puffer Coat" },
    { brand: "Calvin Klein", gender: "women", name: "Wool-Blend Minimalist Oversized Coat" },
    { brand: "Calvin Klein", gender: "women", name: "Modern Structure High-Rise Leggings" },
    { brand: "Calvin Klein", gender: "women", name: "Cropped Institutional Logo Hoodie" },
    { brand: "Calvin Klein", gender: "women", name: "Satin V-Neck Slip Party Dress" },
    { brand: "Calvin Klein", gender: "women", name: "Sculpted Square-Toe Leather Boots" },
    { brand: "Calvin Klein", gender: "women", name: "Smooth Leather Crossbody Camera Bag" },

    // ==========================================
    // REPLAY
    // ==========================================
    { brand: "Replay", gender: "men", name: "Anbass Slim-Fit Superstretch Jeans" },
    { brand: "Replay", gender: "men", name: "Hyperflex Clouds Patented Slim Jeans" },
    { brand: "Replay", gender: "men", name: "Aged Indigo Denim Trucker Jacket" },
    { brand: "Replay", gender: "men", name: "Grover Straight-Fit Rigid Jeans" },
    { brand: "Replay", gender: "men", name: "Plain Cotton Piqué Casual Polo" },
    { brand: "Replay", gender: "men", name: "Logo Print Heavy Crewneck Sweatshirt" },
    { brand: "Replay", gender: "men", name: "Regular-Fit Cotton Cargo Trousers" },
    { brand: "Replay", gender: "men", name: "Waxed Cotton Field Military Jacket" },
    { brand: "Replay", gender: "men", name: "Vintage Distressed Graphic T-Shirt" },
    { brand: "Replay", gender: "men", name: "Chino Hyperflex Ergonomic Trousers" },
    { brand: "Replay", gender: "men", name: "Denim Snap-Button Western Shirt" },
    { brand: "Replay", gender: "men", name: "Lightweight Ripstop Nylon Windbreaker" },
    { brand: "Replay", gender: "men", name: "Wool-Blend Textured Knit Sweater" },
    { brand: "Replay", gender: "men", name: "Military Style Canvas Overshirt" },
    { brand: "Replay", gender: "men", name: "Premium Suede Chelsea Ankle Boots" },
    { brand: "Replay", gender: "men", name: "Distressed Casual Leather Jeans Belt" },
    { brand: "Replay", gender: "men", name: "Ribbed Heavy Knit Winter Beanie" },

    { brand: "Replay", gender: "women", name: "Luz Hyperflex Skinny Super Stretch Jeans" },
    { brand: "Replay", gender: "women", name: "Rose Cropped Straight High-Rise Jeans" },
    { brand: "Replay", gender: "women", name: "Denim Trucker Jacket with Rhinestone Details" },
    { brand: "Replay", gender: "women", name: "High-Waisted Cotton Cargo Trousers" },
    { brand: "Replay", gender: "women", name: "Foil Logo Slim Fit Cotton T-Shirt" },
    { brand: "Replay", gender: "women", name: "Ribbed Knit Bodycon Midi Dress" },
    { brand: "Replay", gender: "women", name: "Faux-Leather Studded Biker Jacket" },
    { brand: "Replay", gender: "women", name: "Denim Short Jumpsuit Dungarees" },
    { brand: "Replay", gender: "women", name: "Oversized Heavy Cotton Loopback Hoodie" },
    { brand: "Replay", gender: "women", name: "V-Neck Fluid Silk-Blend Blouse" },
    { brand: "Replay", gender: "women", name: "Printed Tiered Chiffon Maxi Skirt" },
    { brand: "Replay", gender: "women", name: "Padded Technical Winter Long Coat" },
    { brand: "Replay", gender: "women", name: "Tailored One-Button Casual Blazer" },
    { brand: "Replay", gender: "women", name: "Suede Western Style Pointed Boots" },
    { brand: "Replay", gender: "women", name: "Cropped Graphic Fleece Sweatshirt" },
    { brand: "Replay", gender: "women", name: "Washed Denim High-Waisted Mini Skirt" },
    { brand: "Replay", gender: "women", name: "Grained Leather Studded Shoulder Bag" },

    // ==========================================
    // TOMMY HILFIGER
    // ==========================================
    { brand: "Tommy Hilfiger", gender: "men", name: "1985 Collection Cotton Piqué Polo" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Mercerized Slim Fit Flex Chinos" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Icon Straight Fit Stretch Jeans" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Essential Flag Embroidered Hoodie" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Signature Oxford Cotton Button-Down Shirt" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Packable Down Puffer Warm Jacket" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Organic Cotton Core Crew-Neck Tee" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Denton Straight Fit Comfort Trousers" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Core Premium Cotton Crewneck Sweater" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Classic Denim Flag Trucker Jacket" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Sport Tech Breathable Track Pants" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Flag Logo Quick-Dry Swim Shorts" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Twill Coach Lightweight Jacket" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Casual Regular Fit Linen Shirt" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Essential Clean Leather Cupsole Sneakers" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Corporate Stripe Knit Wool Scarf" },
    { brand: "Tommy Hilfiger", gender: "men", name: "Leather Flag Billfold Wallet" },

    { brand: "Tommy Hilfiger", gender: "women", name: "Heritage Slim Fit Piqué Polo Shirt" },
    { brand: "Tommy Hilfiger", gender: "women", name: "High-Rise Santana Super Skinny Jeans" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Icon Flag Logo Relaxed Sweatshirt" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Signature Stripe Cotton Shirt Dress" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Soft Knit V-Neck Buttoned Cardigan" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Essential Flag Quilted Puffer Vest" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Classic Double-Breasted Cotton Trench Coat" },
    { brand: "Tommy Hilfiger", gender: "women", name: "High-Waisted Wide-Leg Pleated Chinos" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Ribbed Bodycon Polo Midi Dress" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Denim High-Rise Button-Up Mini Skirt" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Flag Logo Cropped Cotton T-Shirt" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Belted Utility Structured Jumpsuit" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Organic Cotton Lounge Leggings" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Tailored Double-Breasted Preppy Blazer" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Leather Flag Plaque Ankle Boots" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Monogram Hardware Leather Crossbody" },
    { brand: "Tommy Hilfiger", gender: "women", name: "Silk Square Monogram Print Scarf" },

    // ==========================================
    // NEW BALANCE
    // ==========================================
    { brand: "New Balance", gender: "men", name: "574 Core Classic Suede Sneakers" },
    { brand: "New Balance", gender: "men", name: "990v6 Made in USA Premium Shoes" },
    { brand: "New Balance", gender: "men", name: "Accelerate 5-Inch Lightweight Shorts" },
    { brand: "New Balance", gender: "men", name: "Essentials Stacked Logo Fleece Hoodie" },
    { brand: "New Balance", gender: "men", name: "327 Retro Lifestyle Nylon Sneakers" },
    { brand: "New Balance", gender: "men", name: "Impact Run Breathable Short Sleeve Top" },
    { brand: "New Balance", gender: "men", name: "Fresh Foam X 1080v13 Cushion Shoes" },
    { brand: "New Balance", gender: "men", name: "Athletics Remixed Zip Track Jacket" },
    { brand: "New Balance", gender: "men", name: "Tenacity Athletic Training Tights" },
    { brand: "New Balance", gender: "men", name: "Sport Essentials Tapered Tech Joggers" },
    { brand: "New Balance", gender: "men", name: "2002R Premium Lifestyle Sneakers" },
    { brand: "New Balance", gender: "men", name: "Relentless Crew-Neck Athletic Sweatshirt" },
    { brand: "New Balance", gender: "men", name: "Hoops Graphic Cotton Basketball Tee" },
    { brand: "New Balance", gender: "men", name: "Core Fleece Comfortable Sweatpants" },
    { brand: "New Balance", gender: "men", name: "Fresh Foam X More Trail Shoes" },
    { brand: "New Balance", gender: "men", name: "Performance Running Adjustable Cap" },
    { brand: "New Balance", gender: "men", name: "Lifestyle Canvas Daily Tote Bag" },

    { brand: "New Balance", gender: "women", name: "574 Core Retro Sneakers Women" },
    { brand: "New Balance", gender: "women", name: "327 Lifestyle Modern Shoes Women" },
    { brand: "New Balance", gender: "women", name: "Accelerate 2.5-Inch Track Running Shorts" },
    { brand: "New Balance", gender: "women", name: "Essentials Stacked Logo Cropped Hoodie" },
    { brand: "New Balance", gender: "women", name: "Fresh Foam X 1080v13 Cushioned Women" },
    { brand: "New Balance", gender: "women", name: "NB Sleek High-Rise Pocket Leggings" },
    { brand: "New Balance", gender: "women", name: "Athletics Mineral Glow Crop T-Shirt" },
    { brand: "New Balance", gender: "women", name: "Impact Run Moisture-Wicking Tank Top" },
    { brand: "New Balance", gender: "women", name: "550 Classic Low-Top Basketball Shoes" },
    { brand: "New Balance", gender: "women", name: "Relentless Fleece Crewneck Pullover" },
    { brand: "New Balance", gender: "women", name: "NB Power X High-Impact Sports Bra" },
    { brand: "New Balance", gender: "women", name: "Transform High-Rise Training Tight" },
    { brand: "New Balance", gender: "women", name: "Nergize Sport Sleek Slip-On Shoes" },
    { brand: "New Balance", gender: "women", name: "Fresh Foam Hierro GORE-TEX Trail" },
    { brand: "New Balance", gender: "women", name: "Sport Fleece Relaxed Fit Joggers" },
    { brand: "New Balance", gender: "women", name: "Performance Running Lightweight Visor" },
    { brand: "New Balance", gender: "women", name: "Lifestyle Everyday Urban Backpack" },

    // ==========================================
    // LACOSTE
    // ==========================================
    { brand: "Lacoste", gender: "men", name: "Classic Fit L.12.12 Cotton Piqué Polo" },
    { brand: "Lacoste", gender: "men", name: "Slim Fit Stretch Gabardine Chinos" },
    { brand: "Lacoste", gender: "men", name: "Sport Breathable Ultra-Dry Piqué T-Shirt" },
    { brand: "Lacoste", gender: "men", name: "Heritage Crew-Neck Unbrushed Sweater" },
    { brand: "Lacoste", gender: "men", name: "Cotton Gabardine Classic Harrington Jacket" },
    { brand: "Lacoste", gender: "men", name: "Court-Drive Technical Mesh Sneakers" },
    { brand: "Lacoste", gender: "men", name: "Sport Tennis Lightweight Woven Shorts" },
    { brand: "Lacoste", gender: "men", name: "Waterproof Hooded Zipper Windbreaker" },
    { brand: "Lacoste", gender: "men", name: "Monogram Jacquard Zip-Up Track Jacket" },
    { brand: "Lacoste", gender: "men", name: "Carnaby Evo Classic Leather Shoes" },
    { brand: "Lacoste", gender: "men", name: "Regular Fit Premium Denim Shirt" },
    { brand: "Lacoste", gender: "men", name: "Lightweight Water-Resistant Puffer Vest" },
    { brand: "Lacoste", gender: "men", name: "Striped Cotton Heavy Rugby Shirt" },
    { brand: "Lacoste", gender: "men", name: "Wool-Blend Classic V-Neck Cardigan" },
    { brand: "Lacoste", gender: "men", name: "Classic Cotton Piqué Adjustable Cap" },
    { brand: "Lacoste", gender: "men", name: "Croco Crew Grained Leather Billfold" },
    { brand: "Lacoste", gender: "men", name: "Signature Embroidered Logo Socks 3-Pack" },

    { brand: "Lacoste", gender: "women", name: "Slim Fit Petit Piqué Iconic Polo" },
    { brand: "Lacoste", gender: "women", name: "Sport Pleated Performance Tennis Skirt" },
    { brand: "Lacoste", gender: "women", name: "Sport Breathable Run Anti-UV T-Shirt" },
    { brand: "Lacoste", gender: "women", name: "Heritage Cable-Knit V-Neck Sweater" },
    { brand: "Lacoste", gender: "women", name: "Long Hooded Drawstring Rain Coat" },
    { brand: "Lacoste", gender: "women", name: "Ziane Chunky Chic Leather Sneakers" },
    { brand: "Lacoste", gender: "women", name: "High-Waisted Woven Track Trousers" },
    { brand: "Lacoste", gender: "women", name: "Cropped Piqué Boxy Polo Shirt" },
    { brand: "Lacoste", gender: "women", name: "Cotton Fleece Hooded Sweatshirt Dress" },
    { brand: "Lacoste", gender: "women", name: "Stretch Cotton Gabardine City Shorts" },
    { brand: "Lacoste", gender: "women", name: "Monogram Jacquard Buttoned Cardigan" },
    { brand: "Lacoste", gender: "women", name: "Knit A-Line Elastic Midi Skirt" },
    { brand: "Lacoste", gender: "women", name: "L.12.12 Concept Large Zip Shopping Tote" },
    { brand: "Lacoste", gender: "women", name: "Anna Reversible Coated Canvas Shopper" },
    { brand: "Lacoste", gender: "women", name: "Fine-Grained Leather Zip Continental Wallet" },
    { brand: "Lacoste", gender: "women", name: "Canvas Crocodile Print Crossbody Bag" },
    { brand: "Lacoste", gender: "women", name: "Classic Wool Blend Ribbed Beanie" },

    // ==========================================
    // VANS
    // ==========================================
    { brand: "Vans", gender: "men", name: "Old Skool Classic Canvas Skate Shoes" },
    { brand: "Vans", gender: "men", name: "Classic Slip-On Durable Core Shoes" },
    { brand: "Vans", gender: "men", name: "Authentic Low-Top Heritage Sneakers" },
    { brand: "Vans", gender: "men", name: "Sk8-Hi Tapered High-Top Skate Shoes" },
    { brand: "Vans", gender: "men", name: "Classic Checkerboard Logo T-Shirt" },
    { brand: "Vans", gender: "men", name: "Core Basics Heavy Fleece Pullover Hoodie" },
    { brand: "Vans", gender: "men", name: "Authentic Chino Glide Relaxed Fit Pants" },
    { brand: "Vans", gender: "men", name: "Off The Wall Graphic Heavyweight Tee" },
    { brand: "Vans", gender: "men", name: "Drill Chore Heavy Cotton Canvas Coat" },
    { brand: "Vans", gender: "men", name: "Range Relaxed Fit Elastic Waist Shorts" },
    { brand: "Vans", gender: "men", name: "Standard Mid Snow MTE Waterproof Boots" },
    { brand: "Vans", gender: "men", name: "Alva Skateboard Collaboration T-Shirt" },
    { brand: "Vans", gender: "men", name: "Torrey Nylon Button-Up Windbreaker Jacket" },
    { brand: "Vans", gender: "men", name: "Suede Chukka Retro Skate Boots" },
    { brand: "Vans", gender: "men", name: "Ward Crossbody Heavy Nylon Pack" },
    { brand: "Vans", gender: "men", name: "Curved Bill Jockey Classic Hat" },
    { brand: "Vans", gender: "men", name: "Classic Ribbed Crew Socks 3-Pack" },

    { brand: "Vans", gender: "women", name: "Old Skool Canvas Platform Sneakers" },
    { brand: "Vans", gender: "women", name: "Classic Slip-On Platform Core Shoes" },
    { brand: "Vans", gender: "women", name: "Authentic Stackform Chunky Platform" },
    { brand: "Vans", gender: "women", name: "Sk8-Hi Tapered Deconstructed Women" },
    { brand: "Vans", gender: "women", name: "Checkerboard Knit Cropped T-Shirt" },
    { brand: "Vans", gender: "women", name: "Together Forever Pullover Fleece Hoodie" },
    { brand: "Vans", gender: "women", name: "Ground Work Corduroy Workwear Dungarees" },
    { brand: "Vans", gender: "women", name: "Flying V Classic Crew Sweatshirt" },
    { brand: "Vans", gender: "women", name: "In The Know Longline Canvas Coat" },
    { brand: "Vans", gender: "women", name: "Range Wide-Leg Elastic Waist Pants" },
    { brand: "Vans", gender: "women", name: "Colfax Lugged Sole Waterproof Boot" },
    { brand: "Vans", gender: "women", name: "Spiral Tie-Dye Oversized T-Shirt" },
    { brand: "Vans", gender: "women", name: "Wind It Up Lightweight Crop Windbreaker" },
    { brand: "Vans", gender: "women", name: "Rigid Denim High-Waisted Mini Skirt" },
    { brand: "Vans", gender: "women", name: "Got This Mini Durable Nylon Backpack" },
    { brand: "Vans", gender: "women", name: "Court Side Classic Baseball Cap" },
    { brand: "Vans", gender: "women", name: "Canoodle No-Show Socks 3-Pack" },

    // ==========================================
    // PUMA
    // ==========================================
    { brand: "Puma", gender: "men", name: "Suede Classic XXI Iconic Sneakers" },
    { brand: "Puma", gender: "men", name: "Essentials Big Logo Fleece Hoodie" },
    { brand: "Puma", gender: "men", name: "T7 Iconic Contrast Stripe Track Jacket" },
    { brand: "Puma", gender: "men", name: "Training Vent Ergonomic Short Sleeve Tee" },
    { brand: "Puma", gender: "men", name: "Cali Court Minimalist Casual Shoes" },
    { brand: "Puma", gender: "men", name: "Run Favorite Tapered Athletic Pants" },
    { brand: "Puma", gender: "men", name: "Velocity Nitro High-Performance Running Shoes" },
    { brand: "Puma", gender: "men", name: "King Pro Firm Ground Soccer Cleats" },
    { brand: "Puma", gender: "men", name: "Power Colorblock Fleece Sweatshirt" },
    { brand: "Puma", gender: "men", name: "dryCELL Training Performance Gym Shorts" },
    { brand: "Puma", gender: "men", name: "Archive T7 Tapered Track Trousers" },
    { brand: "Puma", gender: "men", name: "Evostripe Athletic Full-Zip Hoodie" },
    { brand: "Puma", gender: "men", name: "ESS Padded Water-Resistant Jacket" },
    { brand: "Puma", gender: "men", name: "Popcat 20 Classic Sport Slides" },
    { brand: "Puma", gender: "men", name: "Better Foam Prowl Eco Training Shoes" },
    { brand: "Puma", gender: "men", name: "Grid Performance Mesh Running Cap" },
    { brand: "Puma", gender: "men", name: "Buzz Multi-Pocket Sport Backpack" },

    { brand: "Puma", gender: "women", name: "Mayze Platform Chunky Leather Sneakers" },
    { brand: "Puma", gender: "women", name: "Essentials Logo Fleece Cropped Hoodie" },
    { brand: "Puma", gender: "women", name: "T7 Iconic Track Jacket Women" },
    { brand: "Puma", gender: "women", name: "Run Favorite High-Waisted Running Leggings" },
    { brand: "Puma", gender: "women", name: "Cali Dream Pastel Tones Sneakers" },
    { brand: "Puma", gender: "women", name: "Cruise Rider Retro Lifestyle Shoes" },
    { brand: "Puma", gender: "women", name: "Velocity Nitro Running Shoes Women" },
    { brand: "Puma", gender: "women", name: "Forever Luxe Premium Training Tights" },
    { brand: "Puma", gender: "women", name: "Power Hooded Fleece Lounge Dress" },
    { brand: "Puma", gender: "women", name: "dryCELL High-Waisted Woven Workout Shorts" },
    { brand: "Puma", gender: "women", name: "Evostripe EVOKNIT Seamless T-Shirt" },
    { brand: "Puma", gender: "women", name: "Infuse Soft Oversized Knit Sweatshirt" },
    { brand: "Puma", gender: "women", name: "ESS Padded Slim-Fit Warm Vest" },
    { brand: "Puma", gender: "women", name: "Fluff Faux-Fur Slide Sandals" },
    { brand: "Puma", gender: "women", name: "Better Foam Prowl Slip-On Training Shoes" },
    { brand: "Puma", gender: "women", name: "Classic Cuff Knit Warm Beanie" },
    { brand: "Puma", gender: "women", name: "Phase Compact Sports Daily Backpack" }
];