import type {Metadata} from "next";
import {Source_Sans_3} from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/lib/ScrollToTop";
import { Cormorant_Garamond } from "next/font/google"
import {Toaster} from "sonner";

const cormorant = Cormorant_Garamond({
    variable: "--font-cormorant",
    subsets: ["latin"],
    weight: ["300", "400", "600"],
})

const sourceSans = Source_Sans_3({
    variable: "--source-sans-3",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${sourceSans.variable} ${cormorant.variable} h-full antialiased`}>
        <body className={`${sourceSans.className} min-h-screen flex flex-col`}>
        <ScrollToTop/>
        <Toaster position="bottom-center" richColors/>
        {children}
        </body>
        </html>
    )
}
