import type {Metadata} from "next";
import {Source_Sans_3} from "next/font/google";
import "./globals.css";

const sourceSans = Source_Sans_3({
    variable: "--source-sans-3",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${sourceSans.variable} h-full antialiased`}>
        <body className={`${sourceSans.className} min-h-screen flex flex-col`}>
        {children}
        </body>
        </html>
    )
}
